api:
  entities:
    Training\Bundle\UserNamingBundle\Entity\UserNamingType:
      sorters:
        fields:
          title:
            exclude: false
      filters:
        fields:
          title:
            exclude: false
      fields:
        namingExample:
          data_type: string
          meta_property: true
      actions:
        create:
          fields:
            namingExample:
              exclude: true
        update:
          fields:
            namingExample:
              exclude: true
