datagrids:
  user-naming-types-grid:
    source:
      type: orm
      query:
        select:
          - u.id
          - u.title
          - u.format
        from:
          - { table: Training\Bundle\UserNamingBundle\Entity\UserNamingType, alias: u }

    columns:
      title:
        label: training.usernaming.usernamingtype.title.label
      format:
        label: training.usernaming.usernamingtype.format.label

    sorters:
      columns:
        title:
          data_name: u.title
      default:
        dueDate: DESC

    filters:
      columns:
        title:
          data_name: u.title
          type: string
