navigation:
  menu_config:
    items:
      user_naming_type_list:
        label: training.usernaming.usernamingtype.entity_plural_label
        route: user_naming_type_index
        position: 10
    tree:
      application_menu:
        children:
          system_tab:
            children:
              users_management:
                children:
                  user_naming_type_list: ~
