services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Converter
  training_user_naming_bundle.importexport.data_converter.user_naming_type:
    parent: oro_importexport.data_converter.configurable

  training_user_naming_bundle.importexport.data_converter.template_fixture.user_naming_type:
    parent: oro_importexport.data_converter.template_fixture.configurable

  # Strategy
  training_user_naming_bundle.importexport.strategy.user_naming_type.add_or_replace:
    parent: oro_importexport.strategy.configurable_add_or_replace

  # Export processor
  training_user_naming_bundle.importexport.processor.export.user_naming_type:
    parent: oro_importexport.processor.export_abstract
    calls:
      - [ setDataConverter, [ '@training_user_naming_bundle.importexport.data_converter.user_naming_type' ] ]
    tags:
      -   name: oro_importexport.processor
          type: export
          entity: Training\Bundle\UserNamingBundle\Entity\UserNamingType
          alias: training_user_naming_type

  training_user_naming_bundle.importexport.processor.export_template.user_naming_type:
    parent: oro_importexport.processor.export_abstract
    calls:
      - [ setDataConverter, [ '@training_user_naming_bundle.importexport.data_converter.template_fixture.user_naming_type' ] ]
    tags:
      -   name: oro_importexport.processor
          type: export_template
          entity: Training\Bundle\UserNamingBundle\Entity\UserNamingType
          alias: training_user_naming_type

  # Import processor
  training_user_naming_bundle.importexport.processor.import.user_naming_type:
    parent: oro_importexport.processor.import_abstract
    calls:
      - [ setDataConverter, [ '@training_user_naming_bundle.importexport.data_converter.user_naming_type' ] ]
      - [ setStrategy, [ '@training_user_naming_bundle.importexport.strategy.user_naming_type.add_or_replace' ] ]
    tags:
      -   name: oro_importexport.processor
          type: import
          entity: Training\Bundle\UserNamingBundle\Entity\UserNamingType
          alias: training_user_naming_type_add_or_replace
      -   name: oro_importexport.processor
          type: import_validation
          entity: Training\Bundle\UserNamingBundle\Entity\UserNamingType
          alias: training_user_naming_type_add_or_replace

  # Template fixture
  Training\Bundle\UserNamingBundle\ImportExport\TemplateFixture\UserNamingTypeFixture:
    tags: [ oro_importexport.template_fixture ]

  # Configuration
  Training\Bundle\UserNamingBundle\ImportExport\Configuration\UserNamingTypeImportExportConfigurationProvider:
    tags:
      - { name: oro_importexport.configuration, alias: user_naming_type }
