services:
  Training\Bundle\UserNamingBundle\Api\Processor\Get\NamingExampleGetProcessor:
    arguments:
      - '@Training\Bundle\UserNamingBundle\Provider\FullNameProvider'
    tags:
      -
        name: oro.api.processor
        action: get
        group: finalize
        class: Training\Bundle\UserNamingBundle\Entity\UserNamingType
        priority: -25

  Training\Bundle\UserNamingBundle\Api\Processor\GetList\NamingExampleGetListProcessor:
    arguments:
      - '@Training\Bundle\UserNamingBundle\Provider\FullNameProvider'
    tags:
      -
        name: oro.api.processor
        action: get_list
        group: finalize
        class: Training\Bundle\UserNamingBundle\Entity\UserNamingType
        priority: -25
