services:
  Training\Bundle\UserNamingBundle\Provider\EntityNameProviderDecorator:
    arguments:
      - '@.inner'
      - '@Training\Bundle\UserNamingBundle\Provider\FullNameProvider'
    decorates: oro_locale.entity_name_provider

  Training\Bundle\UserNamingBundle\EventListener\UserViewNamingListener:
    arguments:
      - '@security.authorization_checker'
    tags:
      - {name: kernel.event_listener, event: oro_ui.scroll_data.before.userView, method: onUserView}

  Training\Bundle\UserNamingBundle\Provider\FullNameProvider: ~

  Training\Bundle\UserNamingBundle\Twig\NamingTypeExtension:
    tags:
      - {name: twig.extension}

  Training\Bundle\UserNamingBundle\Twig\FullNameExample:
    arguments:
      - '@Training\Bundle\UserNamingBundle\Provider\FullNameProvider'
    tags:
      - {name: twig.runtime}
